#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const contentDir = path.join(__dirname, "tonyedv");
const outputFile = path.join(__dirname, "grid-data.js");

function parseFrontmatterAndBody(text) {
    text = text.replace(/\r\n/g, "\n");

    const frontmatter = {};
    let body = text;

    if (text.indexOf("---") === 0) {
        const lines = text.split("\n");
        let i;

        for (i = 1; i < lines.length; i++) {
            const line = lines[i];
            if (line.trim() === "---") {
                i++;
                break;
            }
            if (!line.trim()) {
                continue;
            }

            const colonIndex = line.indexOf(":");
            if (colonIndex === -1) {
                continue;
            }

            const key = line.substring(0, colonIndex).trim();
            let value = line.substring(colonIndex + 1).trim();

            if (/^\d+$/.test(value)) {
                value = parseInt(value);
            }
            frontmatter[key] = value;
        }

        body = lines.slice(i).join("\n");
    }

    return { frontmatter: frontmatter, body: body };
}

function build() {
    if (!fs.existsSync(contentDir)) {
        console.error("Content directory not found:", contentDir);
        process.exit(1);
    }

    const files = fs
        .readdirSync(contentDir)
        .filter(function (name) {
            return /\.md$/i.test(name);
        })
        .sort();

    const items = files.map(function (filename) {
        const fullPath = path.join(contentDir, filename);
        const raw = fs.readFileSync(fullPath, "utf8");
        const parsed = parseFrontmatterAndBody(raw);
        const fm = parsed.frontmatter || {};
        const markdown = parsed.body.trim() || "";

        const item = {
            ...fm,
            title: fm.title ? fm.title.replace("\\n", "\n") : "",
            order: /^\d+/.exec(filename)[0],
            source: "tonyedv/" + filename,
            markdown: markdown,
        };

        return item;
    });

    items.sort(function (a, b) {
        return a.order - b.order;
    });

    const header =
        "// This file is generated by build-grid.js. Do not edit by hand.\n";
    const js =
        header + "var GRID_DATA = " + JSON.stringify(items, null, 2) + ";\n";

    fs.writeFileSync(outputFile, js, "utf8");
    console.log(
        "Wrote",
        items.length,
        "items to",
        path.relative(process.cwd(), outputFile)
    );
}

build();


